### ISSUE TITLE
Don't use --show-current

### ISSUE THREAD

**Issue by rohit-gohri** [AbhyudayaSharma/react-git-info#1]
It's a more recent feature in git so not available in all environments,  I updated my local git installation and it works. But it's failing in my CI pipeline because the docker image I'm using has an older version of git (official node:10, which is not that old).

Would be better to use:

`git rev-parse --abbrev-ref HEAD`

as it's more likely to work everywhere.

**Comment by AbhyudayaSharma** [comment]
@rohit-gohri Thanks for creating the issue! I will try to take a look very soon. Maybe you can create a PR before me?
