### ISSUE TITLE
Git tag not being displayed

### ISSUE THREAD

**Issue by limpep** [AbhyudayaSharma/react-git-info#10]
Hi, 

I noticed that git tag is not being displayed. 

```
git log --decorate=full --format=%D%n%h%n%H%n%cI%n%B -n 1 HEAD
HEAD -> refs/heads/main, refs/remotes/origin/main
96df201
96df201ce1fe2f9012c983690e2913b26f889e86
2020-10-04T11:16:08+01:00
fixed fetch issue
```

Here is a list of my tags

```
 git tag
v0.1.0
```

the following command displays tag

```
git log --decorate --all --oneline --graph
* 96df201 (HEAD -> main, origin/main) fixed fetch issue
* 2b951de first commit
* 645d9ee (tag: v0.1.0) first commit
```

**Comment by AbhyudayaSharma** [comment]
@limpep looks like you are on a different commit when you are getting the tag. The commit `96df201` does not have a tag according to the output of `git log --decorate --all --oneline --graph`. The commit `645d9ee` is tagged instead. Try to checkout `645d9ee` and then see if it tag is showing or not.

**Comment by limpep** [comment]
@AbhyudayaSharma you are right, I just realised that 🤦‍♂️, sorry about that. Thanks for you and great library much appreciated.
