### ISSUE TITLE
library is not working when we build it with Jenkins

### ISSUE THREAD

**Issue by bhagyashree-gondaliya** [AbhyudayaSharma/react-git-info#11]
i have used this library to fetch git hash when branch is dev it works fine in dev local run and build but when same dev code build with jenkins it will not return hash value please suggest solution

**Comment by AbhyudayaSharma** [comment]
What errors are you getting? Do you have Git in your build environment?

**Comment by AbhyudayaSharma** [comment]
Closing because no response.
