### ISSUE TITLE
cant find module 'fs', etc

### ISSUE THREAD

**Issue by zhangwuyang-github** [AbhyudayaSharma/react-git-info#27]
![image](https://user-images.githubusercontent.com/82797771/186860201-8f373c3c-8297-465a-8e82-bfc9786bb623.png)
![image](https://user-images.githubusercontent.com/82797771/186860243-d103160d-df38-44ca-80ef-d4b0b2153791.png)

**Comment by AbhyudayaSharma** [comment]
Are you using create-react-app?

**Comment by AbhyudayaSharma** [comment]
Looks like a duplicate of #16. Please reopen if your issue is different.

**Comment by hugocalheira** [comment]
Same error here.
Using Nextjs 13.

![image](https://github.com/AbhyudayaSharma/react-git-info/assets/6580989/2cc6eff6-70eb-4e03-a53f-a527b57d63c7)
![image](https://github.com/AbhyudayaSharma/react-git-info/assets/6580989/955f9f43-dcbc-4e6f-b6d5-ca1f10773260)
