### ISSUE TITLE
Dependency to 'child_process' missing in package.json

### ISSUE THREAD

**Issue by kriede** [AbhyudayaSharma/react-git-info#9]

**Comment by AbhyudayaSharma** [comment]
I'm not sure what you mean by missing `child_process`. `child_process` comes directly from node and doesn't need any npm dependency. What are you trying to do and what errors do you get? Please note that this package is not meant to be used from a browser.

**Comment by kriede** [comment]
Have this error:
```
1>  ERROR in ./node_modules/react-git-info/src/GitInfo.macro.js
1>Module not found : error : Can't resolve 'child_process' in 'C:\Users\k.riede\Documents\GitHub\Pulse-Board\Pulse-BoardWeb\node_modules\react-git-info\src'

```

Anyway, your comment answered my question, thought it is a compile time tool to make git info available in my web application.... have to look for a different approach.

**Comment by AbhyudayaSharma** [comment]
@kriede You can use this if you use Babel and configure `babel-plugin-macros`. Otherwise, look at https://www.npmjs.com/package/simple-git

**Comment by kriede** [comment]
Thank you @AbhyudayaSharma for your support, I'll give it a try!
